version: 2

updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "02:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  reviewers:
  - SDA-SE/bedrock
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
