version: 2

updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "02:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  reviewers:
  - SDA-SE/sda-workforce
  commit-message:
    prefix: fix
    include: scope
  groups:
    plugins:
      prefix: chore
      patterns:
        - org.sonarqube
        - com.diffplug.spotless
        - com.google.cloud.tools.jib
        - org.cyclonedx.bom
    test:
      prefix: test
      patterns:
        - org.junit:junit-bom
        - net.bytebuddy:byte-buddy-parent
        - org.junit.jupiter:junit-jupiter
        - org.junit-pioneer:junit-pioneer
        - org.assertj:assertj-core
        - de.flapdoodle.embed:de.flapdoodle.embed.mongo
        - org.mockito:mockito-junit-jupiter
        - uk.org.webcompere:system-stubs-jupiter
        - org.mockito:mockito-inline
        - org.awaitility:awaitility
        - io.fabric8:kubernetes-server-mock
        - com.squareup.okhttp3:okhttp
  ignore:
    - dependency-name: org.eclipse.jetty:jetty-bom
      update-types: ["version-update:semver-major"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
    - "dependencies"
  commit-message:
    prefix: "chore"
    prefix-development: "chore"
    include: scope
