# configure the semantic-release utility
tagFormat: ${version}
debug: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - ["@semantic-release/exec", { "prepareCmd": "./release-prepare.sh \"${nextRelease.version}\"" }]
branches:
  - name: 'master'
