---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mongodb-operator
  description: |
    Bootstraps databases in existing MongoDB clusters based on a custom MongoDB resource.
  tags:
    - kubernetes
    - operator
  annotations:
    sda.se/summary: |
      A Kubernetes Operator that creates users and databases in existing MongoDB clusters based on a
      custom resource.

      Based on the resource name, a secret is created that contains the dynamically generated
      database name, username and password.

      When the operator is installed in a cluster, a database can be requested with a MongoDB
      resource:

      ```yaml
      apiVersion: persistence.sda-se.com/v1beta1
      kind: MongoDb
      metadata:
        name: my-db
        namespace: test-namespace
      spec:
        database:
          pruneAfterDelete: true # optional, default false
        secret:
          databaseKey: d # optional, default 'database'
          usernameKey: u # optional, default 'username'
          passwordKey: p # optional, default 'password'
      ```

      This will create a database named `test-namespace_my-db` and the user `test-namespace_my-db`
      with read-write access to that database and a secret named `my-db` in `test-namespace`.
      The secret will provide the data `d: test-namespace_my-db`, `u: test-namespace_my-db` and
      `p: <random-password>` (with base64 encoded values).

      When the MongoDB resource is deleted, the database user and the secret are deleted as well.
      If `spec.database.pruneAfterDelete` is true, the whole database with all content will be
      deleted.

      With an appriopriate Kustomize configuration (similar to the configuration required for Sealed
      Secrets), databases created this way can be used in PR deployments with name suffix.
spec:
  type: service
  lifecycle: experimental
  owner: team-mrkaplan
  # TODO: Add a system
  providesApis:
    - mongodbs-crd
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mongodbs-crd
  description: CRD to request a MongoDB database from the mongodb-operator.
  tags:
    - kubernetes
    - operator
  annotations:
    sda.se/summary: |
      A MongoDB custom resource initiates a request for a database for the namespace where it
      is located.
      A database user with access to a database named `[metadata.namespace]_[metadata.name]`
      will be created by the MongoDB Controller in an already existing MongoDB instance.
      A secret containing username and a random password with the same `metadata.name` as this
      custom resource will be provided in the same namespace.
      Currently the database host, port, options and other parameters than username and
      password must be set according the MongoDB instance configured for the cluster in the
      MongoDB Controller.
      The secret and the user will be removed, when this custom resource is deleted.
      The database will be deleted if `spec.database.pruneAfterDelete` is `true`.
spec:
  # Although not officially supported, we can use this type. The spec will be shown as source.
  type: crd
  owner: team-mrkaplan
  # TODO: Add a system
  lifecycle: experimental
  definition:
    $text: ./kustomize/bases/operator/mongodbs-crd.yaml
