site_name: 'MongoDB Operator'

nav:
  - MongoDB Operator: index.md
  - Deployment: deployment.md
  - ArgoCD: argocd.md
  - Usage: usage.md
  - How the MongoDB Operator works: process.md

plugins:
  - techdocs-core

markdown_extensions:
  # Add support for the `--8<--` feature to import files. Remove this as soon as it is
  # part of the techdocs-core plugin: https://github.com/backstage/mkdocs-techdocs-core/issues/20
  - pymdownx.snippets
