apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodbs-crd.yaml
  - mongodb-operator-sa.yaml
  - mongodb-operator-cr.yaml
  - mongodb-operator-crb.yaml
  - mongodb-operator-deploy.yaml

configMapGenerator:
  - name: mongodb-operator-ca-pem
