kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-operator
subjects:
  - kind: ServiceAccount
    name: mongodb-operator
roleRef:
  kind: ClusterRole
  name: mongodb-operator
  apiGroup: rbac.authorization.k8s.io
