apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-operator
  annotations:
    kube-score/ignore: pod-networkpolicy,container-resources
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      serverpod: mongodb-operator
  template:
    metadata:
      labels:
        serverpod: mongodb-operator
    spec:
      serviceAccountName: mongodb-operator
      automountServiceAccountToken: true
      containers:
        - name: operator
          image: localhost:5000/mongodb-operator:local
          imagePullPolicy: Always
          env:
            - name: ENABLE_JSON_LOGGING
              value: "true"
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mongodb-operator
                  key: mongodbConnectionString
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 96Mi
          readinessProbe:
            httpGet:
              port: 8081
              path: /health/readiness
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              port: 8081
              path: /health/liveness
            initialDelaySeconds: 10
