apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: mongodbs.persistence.sda-se.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: persistence.sda-se.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: |
                A MongoDB custom resource initiates a request for a database for the namespace where it
                is located.
                A database user with access to a database named `[metadata.namespace]_[metadata.name]`
                will be created by the MongoDB Controller in an already existing MongoDB instance.
                A secret containing username and a random password with the same `metadata.name` as this
                custom resource will be provided in the same namespace.
                Currently the database host, port, options and other parameters than username and
                password must be set according the MongoDB instance configured for the cluster in the
                MongoDB Controller.
                The secret and the user will be removed, when this custom resource is deleted.
                The database will be deleted if `spec.database.pruneAfterDelete` is `true`.
              type: object
              properties:
                database:
                  description: Specifies handling of the database
                  type: object
                  properties:
                    pruneAfterDelete:
                      description: |
                        If the database **including it's content** should be deleted after the
                        custom resource is removed.
                        This does not affect deletion of the provided secret and the created
                        database user.
                        The secret and the user will be always removed.

                        In development cluster it is useful to clean up databases, especially of PR
                        deployments to keep the database instance small.
                        In a production environment you most likely want to avoid deleting the
                        content accidentally.
                      type: boolean
                      default: false
                    connectionStringOptions:
                      description: |
                        Overwrites the default connection string options used by the MongoDB operator.
                        Connection options are pairs in the following form: name=value
                        Separate options with the ampersand (i.e. &) character name1=value1&name2=value2.
                      type: string
                      example: readPreference=secondaryPreferred&retryWrites=false
                secret:
                  description: Specifies how the secret should be created.
                  type: object
                  properties:
                    databaseKey:
                      description: |
                        The name of the key in the `data` section where the name of the provided
                        database is located.
                      type: string
                      default: database
                      example: MONGODB_USERNAME
                    usernameKey:
                      description: |
                        The name of the key in the `data` section where the username is located.
                      type: string
                      default: username
                      example: MONGODB_USERNAME
                    passwordKey:
                      description: |
                        The name of the key in the `data` section where the password is located.
                      type: string
                      default: password
                      example: MONGODB_PASSWORD
                    connectionStringKey:
                      description: |
                        The name of the key in the `data` section where the connectionString is located.
                      type: string
                      default: connectionString
                      example: MONGODB_CONNECTION_STRING
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: mongodbs
    # singular name to be used as an alias on the CLI and for display
    singular: mongodb
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: MongoDb
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - mongo
