apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb-operator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update"]
  - apiGroups: ["persistence.sda-se.com"]
    resources: ["mongodbs"]
    verbs: ["watch", "list", "get", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    resourceNames:
      - mongodbs.persistence.sda-se.com
    verbs: ["get"]
