apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongodb

resources:
  - mongodb-ns.yaml
  - mongodb-svc.yaml
  - mongodb-deploy.yaml
  - mongoku-ing.yaml
  - mongoku-svc.yaml
  - mongoku-deploy.yaml

secretGenerator:
  - name: mongodb-root
    literals:
      - username=test-root
      - password=test-s3cr3t
  - name: mongoku-mongodb-admin
    literals:
      - mongoDbConnectionUrl=mongodb://test-root:test-s3cr3t@mongodb.mongodb
