name: Combine approved dependency PRs

on:
  workflow_dispatch: # allows you to manually trigger the workflow

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@2909f404763c3177a456e052bdb7f2e85d3a7cb3 # v5.2.0
        with:
          # Regular action token won't trigger workflow for new PR
          github_token: '${{ secrets.GH_RELEASE_TOKEN }}'
          select_label: 'dependencies'
          ci_required: 'false' # Integration test will always fail with dependabot PRs.
          review_required: 'true'
          labels: 'update_collection'
          pr_title: 'Combined Dependency Updates'
          combine_branch_name: 'dependencies/update-collection'
          create_from_scratch: 'true'
