name: Health ArgoCD Integration

# This workflow tests the Lua scripts for MongoDb health status in ArgoCD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    timeout-minutes: 60
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          path: mongodb-operator
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          path: argocd
          repository: "argoproj/argo-cd"
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          # Use the Go version required by the checked out Argo CD revision.
          go-version-file: argocd/go.mod
      - name: Prepare
        run: |
          rm mongodb-operator/health/argocd/persistence.sda-se.com/MongoDb/health_test.lua
          cp -R mongodb-operator/health/argocd/persistence.sda-se.com argocd/resource_customizations
      - name: Verify
        run: |
          ls -alR argocd/resource_customizations/persistence.sda-se.com/MongoDb
          cat argocd/resource_customizations/persistence.sda-se.com/MongoDb/health.lua
          cat argocd/resource_customizations/persistence.sda-se.com/MongoDb/testdata/healthy.yaml
      - name: Test
        run: |
          cd argocd
          go test -v ./util/lua/
