name: Health ArgoCD Local

# This workflow tests the Lua scripts for MongoDb health status in ArgoCD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 60
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

      - uses: leafo/gh-actions-lua@6919171ccf181b826f44b9bca76307b577217377 # v13.0.0
        with:
          luaVersion: "5.4"
      - uses: leafo/gh-actions-luarocks@35d062def313a7699a0d513e996bcf4352f05389 # v6
        with:
          luaVersion: "5.4"
      - name: Test
        run: |
          luarocks --server=https://luarocks.org install lyaml
          lua health/argocd/persistence.sda-se.com/MongoDb/health_test.lua
