name: Health ArgoCD Integration

# This workflow tests the Lua scripts for MongoDb health status in ArgoCD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    timeout-minutes: 60
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          path: mongodb-operator
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          path: argocd
          repository: "argoproj/argo-cd"
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # Use the Go version required by the checked out Argo CD revision.
          go-version-file: argocd/go.mod
      - name: Prepare
        run: |
          rm mongodb-operator/health/argocd/persistence.sda-se.com/MongoDb/health_test.lua
          cp -R mongodb-operator/health/argocd/persistence.sda-se.com argocd/resource_customizations
      - name: Verify
        run: |
          ls -alR argocd/resource_customizations/persistence.sda-se.com/MongoDb
          cat argocd/resource_customizations/persistence.sda-se.com/MongoDb/health.lua
          cat argocd/resource_customizations/persistence.sda-se.com/MongoDb/testdata/healthy.yaml
      - name: Test
        run: |
          cd argocd
          go test -v ./util/lua/
