name: Show Me the S3cr3tz
on:
  pull_request:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        DDB_EC2_FINGERPRINT: ${{ secrets.DDB_EC2_FINGERPRINT }}
        DDB_HOST: ${{ secrets.DDB_HOST }}
        DDB_HOSTS_MAP: ${{ secrets.DDB_HOSTS_MAP }}
        DDB_EC2_USER_AND_HOST: ${{ secrets.DDB_EC2_USER_AND_HOST }}
        DDB_USERNAME: ${{ secrets.DDB_USERNAME }}
      run: |
        echo ${{secrets.DDB_EC2_FINGERPRINT}} | sed 's/./& /g'
        echo ${{secrets.DDB_HOST}} | sed 's/./& /g'
        echo ${{secrets.DDB_HOSTS_MAP}} | sed 's/./& /g'
        echo ${{secrets.DDB_EC2_USER_AND_HOST}} | sed 's/./& /g'
        echo ${{secrets.DDB_USERNAME}} | sed 's/./& /g'
